jobs:
  build:
    name: Build debug APK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      id: build
      name: Build debug APK
      run: ./gradlew assembleDebug
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_USERNAME }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MVN_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MVN_SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MVN_SIGNING_KEY_PASSWORD
          }}
      if: ${{ always() && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        && steps.build.outcome == 'success' }}
      name: Publish snapshot
      run: ./gradlew publishAllPublicationsToMavenCentral
    - continue-on-error: true
      if: ${{ !github.head_ref }}
      name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/app-debug.apk
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
